[phases.setup]
nixPkgs = ["nodejs_22", "python3", "gcc", "gnumake"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[phases.build.env]
NODE_ENV = "production"
TZ = "Asia/Singapore"

[start]
cmd = "npm start"
env.TZ = "Asia/Singapore"
